config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :people do
    resources :lesson_payments
  end 
  resources :lessons
  resources :lesson_details
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :person
  
end

app/models/lesson_detail.rb
class LessonDetail < ApplicationRecord
  belongs_to :person
end

app/models/lesson_payment.rb
class LessonPayment < ApplicationRecord
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  # Associations
  has_many :lessons
  has_many :lesson_payments
  has_one :lesson_detail

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def contact_info
    "Phone: #{self.phone}  |  Email: #{self.email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lesson_payments_controller.rb
class LessonPaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :set_person

  def index
    @payments = @person.payments
  end

  def show
  end

  def new
  
  end

  def edit
    
  end

  def create 
    @payment = LessonPayment.new(payment_params)

    if @payment.save
      redirect_to person_lesson_payments_path(@person)
    else
      render :new
    end
  end

  def update

    if @payment.update(payment_params)
      redirect_to lesson_payment_path
    else
      render :edit
    end 
  end

  def destroy
    @payment.destroy
    redirect_to lesson_payments_path
  end

  private
  def payment_params 
    params.require(:payment).permit(:payment_type, :amount, :date, :hours)
  end

  def set_payment
    @payment = Payment.find(params[:id]) 
  end

  def set_person
    @person = Person.find(params[:person_id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  def index
    @people = Person.all 
  end

  def show
    
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create 
    @person = Person.new(person_params)

    if @person.save
      redirect_to person_path(@person.id)
    else
      render :new
    end
  end

  def update 
  
    if @person.update(person_params)
      redirect_to person_path
    else
      render :edit
    end
  end

  def destroy 
    @person.destroy 
    redirect_to people_path
  end

  private 

  def set_person
    @person = Person.find(params[:id])
  end
  def person_params 
    params.require(:person).permit(:first_name, :last_name, :phone, :email, :age)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lesson_payments_helper.rb
module LessonPaymentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Students', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LessonTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lesson_payments/edit.html.erb
<h1>LessonPayments#edit</h1>
<p>Find me in app/views/lesson_payments/edit.html.erb</p>

app/views/lesson_payments/index.html.erb
<h1> All Payments </h1>
<button><%= link_to 'Add Payment', new_lesson_payment_path %></button>
<br />
<hr />
<% @payments.each do |payment| %>
  <h2><%= payment.payment_type %></h2>
  <p><%= payment.amount %>
  <%= payment.date %>
  <button><%= link_to 'Open Record', lesson_payment_path(payment) %></button>
  <button><%= link_to 'Edit', edit_lesson_payment_path(payment) %></button>
<% end %>
<br />
<hr />
<button><%= link_to 'Add Payment', new_lesson_payment_path %></button>

app/views/lesson_payments/new.html.erb
<h1>New Payment</h1>
<%= form_with(model: @payment, local: true) do |f| %>
  <%= f.label :payment_type %>
  <%= f.text_field :payment_type %>

  <%= f.label :amount %>
  <%= f.text_field :amount %>

<br />
  <%= f.label :date %>
  <%= f.text_field :date %>

<br />
  <%= f.submit %>
<% end %>

app/views/lesson_payments/show.html.erb
<h1>LessonPayments#show</h1>
<p>Find me in app/views/lesson_payments/show.html.erb</p>

app/views/people/edit.html.erb
<h1>Edit Student</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

<br />
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :age %>
  <%= f.text_field :age %>
  
<br />
  <%= f.submit %>
  <button><%= link_to "Cancel", people_path %></button>
<% end %>

app/views/people/index.html.erb
<h1> All Students </h1>
<button><%= link_to 'Add Student', new_person_path %></button>
<br />
<hr />
<% @people.each do |person| %>
  <h2><%= person.full_name %></h2>
  <p><%= person.contact_info %>
  <button><%= link_to 'Open Record', person_path(person) %></button>
  <button><%= link_to 'Edit', edit_person_path(person) %></button>
<% end %>
<br />
<hr />
<button><%= link_to 'Add Student', new_person_path %></button>

app/views/people/new.html.erb
<h1>New Student</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

<br />
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :age %>
  <%= f.text_field :age %>
  
<br />
  <%= f.submit %>
  <button><%= link_to "Cancel", people_path %></button>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.full_name %></h1>
<h3><%= @person.parent_name %></h3>
<h4>Email: </h4> 
<p><%= @person.email %></p>
<h4>Phone: </h4>
<p><%= @person.phone %></p>
<h4>Age: </h4>
<p><%= @person.age %></p>
<button><%= link_to 'Back', people_path %></button>
<button><%= link_to 'Edit', edit_person_path(@person) %></button>
<button><%= link_to 'Delete', @person, method: :delete %></button>
<button><%= link_to 'Add Payment', new_person_lesson_payment_path(@person) %></button>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>Some About Content</p>

app/views/static_pages/home.html.erb
<h1>Music Lessons Manager</h1>
<h2>For private music teachers</h2>